
# Sumber : https://id.wikipedia.org/wiki/Daftar_kota_di_Indonesia_menurut_provinsi
CITY_CHOICES = [
        # Sumatra
        ('banda_aceh', 'Banda Aceh'),
        ('langsa', 'Langsa'),
        ('lhokseumawe', 'Lhokseumawe'),
        ('sabang', 'Sabang'),
        ('subulussalam', 'Subulussalam'),
        ('pangkalpinang', 'Pangkalpinang'),
        ('bengkulu', 'Bengkulu'),
        ('jambi', 'Jambi'),
        ('sungai_penuh', 'Sungai Penuh'),
        ('batam', 'Batam'),
        ('tanjungpinang', 'Tanjungpinang'),
        ('bandar_lampung', 'Bandar Lampung'),
        ('metro', 'Metro'),
        ('dumai', 'Dumai'),
        ('pekanbaru', 'Pekanbaru'),
        ('bukittinggi', 'Bukittinggi'),
        ('padang', 'Padang'),
        ('padang_panjang', 'Padang Panjang'),
        ('pariaman', 'Pariaman'),
        ('payakumbuh', 'Payakumbuh'),
        ('sawahlunto', 'Sawahlunto'),
        ('solok', 'Solok'),
        ('lubuk_linggau', 'Lubuk Linggau'),
        ('pagar_alam', 'Pagar Alam'),
        ('palembang', 'Palembang'),
        ('prabumulih', 'Prabumulih'),
        ('binjai', 'Binjai'),
        ('gunungsitoli', 'Gunungsitoli'),
        ('medan', 'Medan'),
        ('padangsidimpuan', 'Padangsidimpuan'),
        ('pematangsiantar', 'Pematangsiantar'),
        ('sibolga', 'Sibolga'),
        ('tanjungbalai', 'Tanjungbalai'),
        ('tebing_tinggi', 'Tebing Tinggi'),
        
        # Jawa
        ('cilegon', 'Cilegon'),
        ('serang', 'Serang'),
        ('tangerang_selatan', 'Tangerang Selatan'),
        ('tangerang', 'Tangerang'),
        ('yogyakarta', 'Yogyakarta'),
        ('jakarta_barat', 'Jakarta Barat'),
        ('jakarta_pusat', 'Jakarta Pusat'),
        ('jakarta_selatan', 'Jakarta Selatan'),
        ('jakarta_timur', 'Jakarta Timur'),
        ('jakarta_utara', 'Jakarta Utara'),
        ('bandung', 'Bandung'),
        ('bekasi', 'Bekasi'),
        ('bogor', 'Bogor'),
        ('cimahi', 'Cimahi'),
        ('cirebon', 'Cirebon'),
        ('depok', 'Depok'),
        ('sukabumi', 'Sukabumi'),
        ('tasikmalaya', 'Tasikmalaya'),
        ('banjar', 'Banjar'),
        ('magelang', 'Magelang'),
        ('pekalongan', 'Pekalongan'),
        ('salatiga', 'Salatiga'),
        ('semarang', 'Semarang'),
        ('surakarta', 'Surakarta'),
        ('tegal', 'Tegal'),
        ('batu', 'Batu'),
        ('blitar', 'Blitar'),
        ('kediri', 'Kediri'),
        ('madiun', 'Madiun'),
        ('malang', 'Malang'),
        ('mojokerto', 'Mojokerto'),
        ('pasuruan', 'Pasuruan'),
        ('probolinggo', 'Probolinggo'),
        ('surabaya', 'Surabaya'),
        
        # Kalimantan
        ('pontianak', 'Pontianak'),
        ('singkawang', 'Singkawang'),
        ('banjarbaru', 'Banjarbaru'),
        ('banjarmasin', 'Banjarmasin'),
        ('palangka_raya', 'Palangka Raya'),
        ('balikpapan', 'Balikpapan'),
        ('bontang', 'Bontang'),
        ('samarinda', 'Samarinda'),
        ('nusantara', 'Nusantara'),
        ('tarakan', 'Tarakan'),
        
        # Sulawesi
        ('gorontalo', 'Gorontalo'),
        ('makassar', 'Makassar'),
        ('palopo', 'Palopo'),
        ('parepare', 'Parepare'),
        ('palu', 'Palu'),
        ('baubau', 'Baubau'),
        ('kendari', 'Kendari'),
        ('bitung', 'Bitung'),
        ('kotamobagu', 'Kotamobagu'),
        ('manado', 'Manado'),
        ('tomohon', 'Tomohon'),
        
        # Bali dan Nusa Tenggara
        ('denpasar', 'Denpasar'),
        ('bima', 'Bima'),
        ('mataram', 'Mataram'),
        ('kupang', 'Kupang'),
        
        # Maluku dan Papua
        ('ternate', 'Ternate'),
        ('tidore_kepulauan', 'Tidore Kepulauan'),
        ('ambon', 'Ambon'),
        ('tual', 'Tual'),
        ('sorong', 'Sorong'),
        ('jayapura', 'Jayapura'),
    ]

SPORT_CHOICES = [
    ('football', 'Football'),
    ('basketball', 'Basketball'),
    ('badminton', 'Badminton'),
    ('tennis', 'Tennis'),
    ('running', 'Running'),
    ('cycling', 'Cycling'),
    ('swimming', 'Swimming'),
    ('volleyball', 'Volleyball'),
]

SKILL_CHOICES = [
    ('beginner', 'Beginner'),
    ('intermediate', 'Intermediate'),
    ('advanced', 'Advanced'),
]