
# Sumber : https://id.wikipedia.org/wiki/Daftar_kota_di_Indonesia_menurut_provinsi
CITY_CHOICES = [
    ('ambon', 'Ambon'),
    ('banda_aceh', 'Banda Aceh'),
    ('bandar_lampung', 'Bandar Lampung'),
    ('bandung', 'Bandung'),
    ('banjar', 'Banjar'),
    ('banjarbaru', 'Banjarbaru'),
    ('banjarmasin', 'Banjarmasin'),
    ('batu', 'Batu'),
    ('batam', 'Batam'),
    ('baubau', 'Baubau'),
    ('bekasi', 'Bekasi'),
    ('bengkulu', 'Bengkulu'),
    ('bima', 'Bima'),
    ('binjai', 'Binjai'),
    ('bitung', 'Bitung'),
    ('blitar', 'Blitar'),
    ('bogor', 'Bogor'),
    ('bontang', 'Bontang'),
    ('bukittinggi', 'Bukittinggi'),
    ('cilegon', 'Cilegon'),
    ('cimahi', 'Cimahi'),
    ('cirebon', 'Cirebon'),
    ('denpasar', 'Denpasar'),
    ('depok', 'Depok'),
    ('dumai', 'Dumai'),
    ('gorontalo', 'Gorontalo'),
    ('gunungsitoli', 'Gunungsitoli'),
    ('jakarta_barat', 'Jakarta Barat'),
    ('jakarta_pusat', 'Jakarta Pusat'),
    ('jakarta_selatan', 'Jakarta Selatan'),
    ('jakarta_timur', 'Jakarta Timur'),
    ('jakarta_utara', 'Jakarta Utara'),
    ('jambi', 'Jambi'),
    ('jayapura', 'Jayapura'),
    ('kediri', 'Kediri'),
    ('kendari', 'Kendari'),
    ('kotamobagu', 'Kotamobagu'),
    ('kupang', 'Kupang'),
    ('langsa', 'Langsa'),
    ('lhokseumawe', 'Lhokseumawe'),
    ('lubuk_linggau', 'Lubuk Linggau'),
    ('madiun', 'Madiun'),
    ('magelang', 'Magelang'),
    ('makassar', 'Makassar'),
    ('malang', 'Malang'),
    ('manado', 'Manado'),
    ('mataram', 'Mataram'),
    ('medan', 'Medan'),
    ('metro', 'Metro'),
    ('mojokerto', 'Mojokerto'),
    ('nusantara', 'Nusantara'),
    ('padang', 'Padang'),
    ('padang_panjang', 'Padang Panjang'),
    ('padangsidimpuan', 'Padangsidimpuan'),
    ('pagar_alam', 'Pagar Alam'),
    ('palangka_raya', 'Palangka Raya'),
    ('palembang', 'Palembang'),
    ('palopo', 'Palopo'),
    ('palu', 'Palu'),
    ('pangkalpinang', 'Pangkalpinang'),
    ('pariaman', 'Pariaman'),
    ('parepare', 'Parepare'),
    ('pasuruan', 'Pasuruan'),
    ('payakumbuh', 'Payakumbuh'),
    ('pekalongan', 'Pekalongan'),
    ('pekanbaru', 'Pekanbaru'),
    ('pematangsiantar', 'Pematangsiantar'),
    ('pontianak', 'Pontianak'),
    ('prabumulih', 'Prabumulih'),
    ('probolinggo', 'Probolinggo'),
    ('sabang', 'Sabang'),
    ('salatiga', 'Salatiga'),
    ('samarinda', 'Samarinda'),
    ('sawahlunto', 'Sawahlunto'),
    ('semarang', 'Semarang'),
    ('serang', 'Serang'),
    ('sibolga', 'Sibolga'),
    ('singkawang', 'Singkawang'),
    ('solok', 'Solok'),
    ('sorong', 'Sorong'),
    ('subulussalam', 'Subulussalam'),
    ('sukabumi', 'Sukabumi'),
    ('sungai_penuh', 'Sungai Penuh'),
    ('surabaya', 'Surabaya'),
    ('surakarta', 'Surakarta'),
    ('tangerang', 'Tangerang'),
    ('tangerang_selatan', 'Tangerang Selatan'),
    ('tanjungbalai', 'Tanjungbalai'),
    ('tanjungpinang', 'Tanjungpinang'),
    ('tarakan', 'Tarakan'),
    ('tasikmalaya', 'Tasikmalaya'),
    ('tebing_tinggi', 'Tebing Tinggi'),
    ('tegal', 'Tegal'),
    ('ternate', 'Ternate'),
    ('tidore_kepulauan', 'Tidore Kepulauan'),
    ('tomohon', 'Tomohon'),
    ('tual', 'Tual'),
    ('yogyakarta', 'Yogyakarta'),
]

SPORT_CHOICES = [
    ('football', 'Football'),
    ('basketball', 'Basketball'),
    ('badminton', 'Badminton'),
    ('tennis', 'Tennis'),
    ('running', 'Running'),
    ('cycling', 'Cycling'),
    ('swimming', 'Swimming'),
    ('volleyball', 'Volleyball'),
]

SKILL_CHOICES = [
    ('beginner', 'Beginner'),
    ('intermediate', 'Intermediate'),
    ('advanced', 'Advanced'),
]