# Generated by Django 5.2.6 on 2025-10-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
