# Generated by Django 5.2.7 on 2025-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
