# Generated by Django 5.2.7 on 2025-10-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_discovery', '0002_event_thumbnail'),
        ('event_discovery', '0003_alter_event_id'),
    ]

    operations = [
    ]
