# Generated by Django 5.2.7 on 2025-10-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_discovery', '0004_merge_0002_event_thumbnail_0003_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='thumbnail_url',
        ),
    ]
