# Generated by Django 5.2.6 on 2025-10-24 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('city', models.CharField(choices=[('ambon', 'Ambon'), ('banda_aceh', 'Banda Aceh'), ('bandar_lampung', 'Bandar Lampung'), ('bandung', 'Bandung'), ('banjar', 'Banjar'), ('banjarbaru', 'Banjarbaru'), ('banjarmasin', 'Banjarmasin'), ('batu', 'Batu'), ('batam', 'Batam'), ('baubau', 'Baubau'), ('bekasi', 'Bekasi'), ('bengkulu', 'Bengkulu'), ('bima', 'Bima'), ('binjai', 'Binjai'), ('bitung', 'Bitung'), ('blitar', 'Blitar'), ('bogor', 'Bogor'), ('bontang', 'Bontang'), ('bukittinggi', 'Bukittinggi'), ('cilegon', 'Cilegon'), ('cimahi', 'Cimahi'), ('cirebon', 'Cirebon'), ('denpasar', 'Denpasar'), ('depok', 'Depok'), ('dumai', 'Dumai'), ('gorontalo', 'Gorontalo'), ('gunungsitoli', 'Gunungsitoli'), ('jakarta_barat', 'Jakarta Barat'), ('jakarta_pusat', 'Jakarta Pusat'), ('jakarta_selatan', 'Jakarta Selatan'), ('jakarta_timur', 'Jakarta Timur'), ('jakarta_utara', 'Jakarta Utara'), ('jambi', 'Jambi'), ('jayapura', 'Jayapura'), ('kediri', 'Kediri'), ('kendari', 'Kendari'), ('kotamobagu', 'Kotamobagu'), ('kupang', 'Kupang'), ('langsa', 'Langsa'), ('lhokseumawe', 'Lhokseumawe'), ('lubuk_linggau', 'Lubuk Linggau'), ('madiun', 'Madiun'), ('magelang', 'Magelang'), ('makassar', 'Makassar'), ('malang', 'Malang'), ('manado', 'Manado'), ('mataram', 'Mataram'), ('medan', 'Medan'), ('metro', 'Metro'), ('mojokerto', 'Mojokerto'), ('nusantara', 'Nusantara'), ('padang', 'Padang'), ('padang_panjang', 'Padang Panjang'), ('padangsidimpuan', 'Padangsidimpuan'), ('pagar_alam', 'Pagar Alam'), ('palangka_raya', 'Palangka Raya'), ('palembang', 'Palembang'), ('palopo', 'Palopo'), ('palu', 'Palu'), ('pangkalpinang', 'Pangkalpinang'), ('pariaman', 'Pariaman'), ('parepare', 'Parepare'), ('pasuruan', 'Pasuruan'), ('payakumbuh', 'Payakumbuh'), ('pekalongan', 'Pekalongan'), ('pekanbaru', 'Pekanbaru'), ('pematangsiantar', 'Pematangsiantar'), ('pontianak', 'Pontianak'), ('prabumulih', 'Prabumulih'), ('probolinggo', 'Probolinggo'), ('sabang', 'Sabang'), ('salatiga', 'Salatiga'), ('samarinda', 'Samarinda'), ('sawahlunto', 'Sawahlunto'), ('semarang', 'Semarang'), ('serang', 'Serang'), ('sibolga', 'Sibolga'), ('singkawang', 'Singkawang'), ('solok', 'Solok'), ('sorong', 'Sorong'), ('subulussalam', 'Subulussalam'), ('sukabumi', 'Sukabumi'), ('sungai_penuh', 'Sungai Penuh'), ('surabaya', 'Surabaya'), ('surakarta', 'Surakarta'), ('tangerang', 'Tangerang'), ('tangerang_selatan', 'Tangerang Selatan'), ('tanjungbalai', 'Tanjungbalai'), ('tanjungpinang', 'Tanjungpinang'), ('tarakan', 'Tarakan'), ('tasikmalaya', 'Tasikmalaya'), ('tebing_tinggi', 'Tebing Tinggi'), ('tegal', 'Tegal'), ('ternate', 'Ternate'), ('tidore_kepulauan', 'Tidore Kepulauan'), ('tomohon', 'Tomohon'), ('tual', 'Tual'), ('yogyakarta', 'Yogyakarta')], max_length=50)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SportPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('volleyball', 'Volleyball')], max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sport_type')},
            },
        ),
    ]
